
const imageData = [
  {
    id: 1,
    src: '../../Components/Assets/image1.avif',
    alt: 'Bed Room',
    category : 'bed',
  },
  {
    id: 2,
    src: '../../Components/Assets/image2.jpg',
    alt: 'Sofa',
    category: 'sofa',
  },
  {
    id: 3,
    src: '../../Components/Assets/image6.webp',
    alt: 'Couch',
    category:'couch',
  },
  {
    id: 4,
    src: '../../Components/Assets/image7.avif',
    alt: 'Dinning Set',
    category: 'Dinning Set',
  },
  {
    id: 5,
    src: '../../Components/Assets/image8.avif',
    alt: 'Tea Table',
    category: 'Tea Table'
  },
];
export default imageData;

export const category = [
    {
      id: 1,
      src: '../../Components/Assets/image1.avif',
      alt: 'Bed',
      category : 'bed',
    },
    {
      id: 2,
      src: '../../Components/Assets/image2.jpg',
      alt: 'Sofa',
      category: 'sofa',
    },
    {
      id: 3,
      src: '../../Components/Assets/image6.webp',
      alt: 'Couch',
      category:'couch',
    },
    {
      id: 4,
      src: '../../Components/Assets/image7.avif',
      alt: 'Tea Table',
      category: 'Tea Table'
    },
    {
      id: 5,
      src: '../../Components/Assets/image8.avif',
      alt: 'Dinning Set',
      category: 'Dinning Set',
    },
    {
      id: 6,
      src: '../../Components/Assets/image1.avif',
      alt: 'Dressing Table',
      category: 'Dressing Table'
    },
    {
      id: 7,
      src: '../../Components/Assets/image2.jpg',
      alt: 'Wardrobe',
      category: 'Wardrobe'
    },
    {
      id: 8,
      src: '../../Components/Assets/image6.webp',
      alt: 'Consols',
      category: 'consols'
    },
    {
      id: 9,
      src: '../../Components/Assets/image7.avif',
      alt: 'Wooden Chair',
      category: 'Modern Chair'
    },
    // {
    //   id: 10,
    //   src: '../../Components/Assets/image8.avif',
    //   alt: 'Sofa Chair',
    // },
    {
      id: 11,
      src: '../../Components/Assets/image1.avif',
      alt: 'Small Coffee Table',
      category: 'Small Coffee Table'
    },
    {
      id: 12,
      src: '../../Components/Assets/image2.jpg',
      alt: 'Book Shelf',
      category: 'Book Shelf'
    },
    {
      id: 13,
      src: '../../Components/Assets/image6.webp',
      alt: 'Office Table',
      category: 'Office Table'
    },
]

export const sofa = [
  {
    id: 1,
    src : '/Assets/sofa1.jpg',
    alt : 'sofa 1',
    category: 'sofa',
    height: '85 cm',
    width: '200 cm',
    depth: '90 cm',
    weight: '50 kg',
    material: 'Fabric',
    color: 'Blue',
    price: '$599',
  },
  {  
    id: 2,
    src : '/Assets/sofa2.jpg',
    alt : 'sofa 2',
    category: 'sofa',
    height: '85 cm',
    width: '200 cm',
    depth: '90 cm',
    weight: '50 kg',
    material: 'Fabric',
    color: 'Blue',
    price: '$599',
  },
  {
    id: 3,
    src : '/Assets/sofa3.jpg',
    alt : 'sofa 3',
    height: '85 cm',
    width: '200 cm',
    depth: '90 cm',
    weight: '50 kg',
    material: 'Fabric',
    color: 'Blue',
    price: '$599',
  },
  {
    id: 4,
    src : '/Assets/sofa4.jpg',
    alt : 'sofa 4',
    height: '85 cm',
    width: '200 cm',
    depth: '90 cm',
    weight: '50 kg',
    material: 'Fabric',
    color: 'Blue',
    price: '$599',
  },
  {
    id: 5,
    src : '/Assets/sofa5.jpg',
    alt : 'sofa 5',
    height: '85 cm',
    width: '200 cm',
    depth: '90 cm',
    weight: '50 kg',
    material: 'Fabric',
    color: 'Blue',
    price: '$599',
  },
  {
    id: 6,
    src : '/Assets/sofa6.jpg',
    alt : 'sofa 6',
    height: '85 cm',
    width: '200 cm',
    depth: '90 cm',
    weight: '50 kg',
    material: 'Fabric',
    color: 'Blue',
    price: '$599',
  },
  {
    id: 7,
    src : '/Assets/sofa7.jpg',
    alt : 'sofa 7',
    height: '85 cm',
    width: '200 cm',
    depth: '90 cm',
    weight: '50 kg',
    material: 'Fabric',
    color: 'Blue',
    price: '$599',
  },
  {
    id: 8,
    src : '/Assets/sofa8.jpg',
    alt : 'sofa 8',
    height: '85 cm',
    width: '200 cm',
    depth: '90 cm',
    weight: '50 kg',
    material: 'Fabric',
    color: 'Blue',
    price: '$599',
  },
  {
    id: 9,
    src : '/Assets/sofa9.jpg',
    alt : 'sofa 9',
    height: '85 cm',
    width: '200 cm',
    depth: '90 cm',
    weight: '50 kg',
    material: 'Fabric',
    color: 'Blue',
    price: '$599',
  },
]

export const bed = [
  {
    id:1,
    src : '/Assets/bed1.jpg',
    alt : 'bed1',
    height: '100 cm',
    width: '200 cm',
    depth: '150 cm',
    weight: '80 kg',
    material: 'Wood',
    color: 'Dark Brown',
    price: '$899',
  },
  {
    id:2,
    src : '/Assets/bed2.jpg',
    alt : 'bed1',
    height: '100 cm',
    width: '200 cm',
    depth: '150 cm',
    weight: '80 kg',
    material: 'Wood',
    color: 'Dark Brown',
    price: '$899',
  },
  {
    id:3,
    src : '/Assets/bed3.jpg',
    alt : 'bed1',
    height: '100 cm',
    width: '200 cm',
    depth: '150 cm',
    weight: '80 kg',
    material: 'Wood',
    color: 'Dark Brown',
    price: '$899',
  },
  {
    id:4,
    src : '/Assets/bed4.jpg',
    alt : 'bed1',
    height: '100 cm',
    width: '200 cm',
    depth: '150 cm',
    weight: '80 kg',
    material: 'Wood',
    color: 'Dark Brown',
    price: '$899',
  },
  {
    id:5,
    src : '/Assets/bed5.jpg',
    alt : 'bed1',
    height: '100 cm',
    width: '200 cm',
    depth: '150 cm',
    weight: '80 kg',
    material: 'Wood',
    color: 'Dark Brown',
    price: '$899',
  },
  {
    id:6,
    src : '/Assets/bed6.jpg',
    alt : 'bed1',
    height: '100 cm',
    width: '200 cm',
    depth: '150 cm',
    weight: '80 kg',
    material: 'Wood',
    color: 'Dark Brown',
    price: '$899',
  },
  {
    id:7,
    src : '/Assets/bed7.jpg',
    alt : 'bed1',
    height: '100 cm',
    width: '200 cm',
    depth: '150 cm',
    weight: '80 kg',
    material: 'Wood',
    color: 'Dark Brown',
    price: '$899',
  },
  {
    id:8,
    src : '/Assets/bed8.jpg',
    alt : 'bed1',
    height: '100 cm',
    width: '200 cm',
    depth: '150 cm',
    weight: '80 kg',
    material: 'Wood',
    color: 'Dark Brown',
    price: '$899',
  },
  {
    id:9,
    src : '/Assets/bed9.jpg',
    alt : 'bed1',
    height: '100 cm',
    width: '200 cm',
    depth: '150 cm',
    weight: '80 kg',
    material: 'Wood',
    color: 'Dark Brown',
    price: '$899',
  },
  {
    id:10,
    src : '/Assets/bed10.jpg',
    alt : 'bed1',
    height: '100 cm',
    width: '200 cm',
    depth: '150 cm',
    weight: '80 kg',
    material: 'Wood',
    color: 'Dark Brown',
    price: '$899',
  }
]

export const couch = [
  {
    id:1,
    src : '/Assets/couch1.jpg',
    alt : 'couch1',
    height: '100 cm',
    width: '200 cm',
    depth: '150 cm',
    weight: '80 kg',
    material: 'Wood',
    color: 'Dark Brown',
    price: '$899',
  },
  {
    id:2,
    src : '/Assets/couch2.jpg',
    alt : 'couch1',
    height: '100 cm',
    width: '200 cm',
    depth: '150 cm',
    weight: '80 kg',
    material: 'Wood',
    color: 'Dark Brown',
    price: '$899',
  },
  {
    id:3,
    src : '/Assets/couch3.jpg',
    alt : 'couch1',
    height: '100 cm',
    width: '200 cm',
    depth: '150 cm',
    weight: '80 kg',
    material: 'Wood',
    color: 'Dark Brown',
    price: '$899',
  },
  {
    id:4,
    src : '/Assets/couch4.jpg',
    alt : 'couch1',
    height: '100 cm',
    width: '200 cm',
    depth: '150 cm',
    weight: '80 kg',
    material: 'Wood',
    color: 'Dark Brown',
    price: '$899',
  }
]

export const TeaTable = [
  {
    id:1,
    src : '/Assets/TT1.jpg',
    alt : 'Tea Table',
    height: '100 cm',
    width: '200 cm',
    depth: '150 cm',
    weight: '80 kg',
    material: 'Wood',
    color: 'Dark Brown',
    price: '$899',
  },
  {
    id:2,
    src : '/Assets/TT2.jpg',
    alt : 'Tea Table',
    height: '100 cm',
    width: '200 cm',
    depth: '150 cm',
    weight: '80 kg',
    material: 'Wood',
    color: 'Dark Brown',
    price: '$899',
  },
  {
    id:3,
    src : '/Assets/TT3.jpg',
    alt : 'Tea Table',
    height: '100 cm',
    width: '200 cm',
    depth: '150 cm',
    weight: '80 kg',
    material: 'Wood',
    color: 'Dark Brown',
    price: '$899',
  },
  {
    id:4,
    src : '/Assets/TT4.jpg',
    alt : 'Tea Table',
    height: '100 cm',
    width: '200 cm',
    depth: '150 cm',
    weight: '80 kg',
    material: 'Wood',
    color: 'Dark Brown',
    price: '$899',
  },
]

export const DinningSet = [
  {
    id:1,
    src : '/Assets/DinningSet1.jpg',
    alt : 'Dinning Set',
    height: '100 cm',
    width: '200 cm',
    depth: '150 cm',
    weight: '80 kg',
    material: 'Wood',
    color: 'Dark Brown',
    price: '$899',
  },
  {
    id:2,
    src : '/Assets/DinningSet2.jpg',
    alt : 'Dinning Set',
    height: '100 cm',
    width: '200 cm',
    depth: '150 cm',
    weight: '80 kg',
    material: 'Wood',
    color: 'Dark Brown',
    price: '$899',
  },
  {
    id:3,
    src : '/Assets/DinningSet3.jpg',
    alt : 'Dinning Set',
    height: '100 cm',
    width: '200 cm',
    depth: '150 cm',
    weight: '80 kg',
    material: 'Wood',
    color: 'Dark Brown',
    price: '$899',
  },
  {
    id:4,
    src : '/Assets/DinningSet4.jpg',
    alt : 'Dinning Set',
    height: '100 cm',
    width: '200 cm',
    depth: '150 cm',
    weight: '80 kg',
    material: 'Wood',
    color: 'Dark Brown',
    price: '$899',
  },
]

export const Wardrobe = [
  {
    id: 1,
    src : '/Assets/wardrobe1.jpg',
    alt : 'Wardrobe',
    height: '100 cm',
    width: '200 cm',
    depth: '150 cm',
    weight: '80 kg',
    material: 'Wood',
    color: 'Dark Brown',
    price: '$899',
  },
  {
    id: 2,
    src : '/Assets/wardrobe2.jpg',
    alt : 'Wardrobe'
  },
  {
    id: 3,
    src : '/Assets/wardrobe3.jpg',
    alt : 'Wardrobe',
    height: '100 cm',
    width: '200 cm',
    depth: '150 cm',
    weight: '80 kg',
    material: 'Wood',
    color: 'Dark Brown',
    price: '$899',
  },
  {
    id: 4,
    src : '/Assets/wardrobe4.jpg',
    alt : 'Wardrobe',
    height: '100 cm',
    width: '200 cm',
    depth: '150 cm',
    weight: '80 kg',
    material: 'Wood',
    color: 'Dark Brown',
    price: '$899',
  },
]

export const consols = [
  {
    id: 1,
    src : '/Assets/console1.jpg',
    alt : 'consols',
    height: '100 cm',
    width: '200 cm',
    depth: '150 cm',
    weight: '80 kg',
    material: 'Wood',
    color: 'Dark Brown',
    price: '$899',
  },
  {
    id: 2,
    src : '/Assets/console2.jpg',
    alt : 'consols',
    height: '100 cm',
    width: '200 cm',
    depth: '150 cm',
    weight: '80 kg',
    material: 'Wood',
    color: 'Dark Brown',
    price: '$899',
  },
  {
    id: 3,
    src : '/Assets/console3.jpg',
    alt : 'consols',
    height: '100 cm',
    width: '200 cm',
    depth: '150 cm',
    weight: '80 kg',
    material: 'Wood',
    color: 'Dark Brown',
    price: '$899',
  },
  {
    id: 4,
    src : '/Assets/console4.jpg',
    alt : 'consols',
    height: '100 cm',
    width: '200 cm',
    depth: '150 cm',
    weight: '80 kg',
    material: 'Wood',
    color: 'Dark Brown',
    price: '$899',
  },
]

export const DressingTable = [
  {
    id: 1,
    src : '/Assets/DressingTable1.jpg',
    alt : 'Dressing Table',
    height: '100 cm',
    width: '200 cm',
    depth: '150 cm',
    weight: '80 kg',
    material: 'Wood',
    color: 'Dark Brown',
    price: '$899',
  },
  {
    id: 2,
    src : '/Assets/DressingTable2.jpg',
    alt : 'Dressing Table',
    height: '100 cm',
    width: '200 cm',
    depth: '150 cm',
    weight: '80 kg',
    material: 'Wood',
    color: 'Dark Brown',
    price: '$899',
  },
  {
    id: 3,
    src : '/Assets/DressingTable3.jpg',
    alt : 'Dressing Table',
    height: '100 cm',
    width: '200 cm',
    depth: '150 cm',
    weight: '80 kg',
    material: 'Wood',
    color: 'Dark Brown',
    price: '$899',
  },
  {
    id: 4,
    src : '/Assets/DressingTable4.jpg',
    alt : 'Dressing Table',
    height: '100 cm',
    width: '200 cm',
    depth: '150 cm',
    weight: '80 kg',
    material: 'Wood',
    color: 'Dark Brown',
    price: '$899',
  },
]

export const ModernChair = [
  {
    id: 1,
    src : '/Assets/ModernChair1.jpg',
    alt : 'Modern Chair',
    height: '100 cm',
    width: '200 cm',
    depth: '150 cm',
    weight: '80 kg',
    material: 'Wood',
    color: 'Dark Brown',
    price: '$899',
  },
  {
    id: 2,
    src : '/Assets/ModernChair2.jpg',
    alt : 'Modern Chair',
    height: '100 cm',
    width: '200 cm',
    depth: '150 cm',
    weight: '80 kg',
    material: 'Wood',
    color: 'Dark Brown',
    price: '$899',
  },
  {
    id: 3,
    src : '/Assets/ModernChair3.jpg',
    alt : 'Modern Chair',
    height: '100 cm',
    width: '200 cm',
    depth: '150 cm',
    weight: '80 kg',
    material: 'Wood',
    color: 'Dark Brown',
    price: '$899',
  },
  {
    id: 4,
    src : '/Assets/ModernChair4.jpg',
    alt : 'Modern Chair',
    height: '100 cm',
    width: '200 cm',
    depth: '150 cm',
    weight: '80 kg',
    material: 'Wood',
    color: 'Dark Brown',
    price: '$899',
  },
]

export const SmallCoffeeTable = [
  {
    id: 1,
    src : '/Assets/coffeeTable1.jpg',
    alt : 'Coffee Table',
    height: '100 cm',
    width: '200 cm',
    depth: '150 cm',
    weight: '80 kg',
    material: 'Wood',
    color: 'Dark Brown',
    price: '$899',
  },
  {
    id: 2,
    src : '/Assets/coffeeTable2.jpg',
    alt : 'Coffee Table',
    height: '100 cm',
    width: '200 cm',
    depth: '150 cm',
    weight: '80 kg',
    material: 'Wood',
    color: 'Dark Brown',
    price: '$899',
  },
  {
    id: 3,
    src : '/Assets/coffeeTable3.jpg',
    alt : 'Coffee Table',
    height: '100 cm',
    width: '200 cm',
    depth: '150 cm',
    weight: '80 kg',
    material: 'Wood',
    color: 'Dark Brown',
    price: '$899',
  },
  {
    id: 4,
    src : '/Assets/coffeeTable4.jpg',
    alt : 'Coffee Table',
    height: '100 cm',
    width: '200 cm',
    depth: '150 cm',
    weight: '80 kg',
    material: 'Wood',
    color: 'Dark Brown',
    price: '$899',
  },
]

export const BookShelf = [
  {
    id: 1,
    src : '/Assets/BookShelf1.jpg',
    alt : 'Book Shelf',
    height: '100 cm',
    width: '200 cm',
    depth: '150 cm',
    weight: '80 kg',
    material: 'Wood',
    color: 'Dark Brown',
    price: '$899',
  },
  {
    id: 2,
    src : '/Assets/BookShelf2.jpg',
    alt : 'Book Shelf',
    height: '100 cm',
    width: '200 cm',
    depth: '150 cm',
    weight: '80 kg',
    material: 'Wood',
    color: 'Dark Brown',
    price: '$899',
  },
  {
    id: 3,
    src : '/Assets/BookShelf3.jpg',
    alt : 'Book Shelf',
    height: '100 cm',
    width: '200 cm',
    depth: '150 cm',
    weight: '80 kg',
    material: 'Wood',
    color: 'Dark Brown',
    price: '$899',
  },
  {
    id: 4,
    src : '/Assets/BookShelf4.jpg',
    alt : 'Book Shelf',
    height: '100 cm',
    width: '200 cm',
    depth: '150 cm',
    weight: '80 kg',
    material: 'Wood',
    color: 'Dark Brown',
    price: '$899',
  },
]

export const OfficeTable = [
  {
    id: 1,
    src : '/Assets/OfficeTable1.jpg',
    alt : 'Office Table',
    height: '100 cm',
    width: '200 cm',
    depth: '150 cm',
    weight: '80 kg',
    material: 'Wood',
    color: 'Dark Brown',
    price: '$899',
  },
  {
    id: 2,
    src : '/Assets/OfficeTable2.jpg',
    alt : 'Office Table',
    height: '100 cm',
    width: '200 cm',
    depth: '150 cm',
    weight: '80 kg',
    material: 'Wood',
    color: 'Dark Brown',
    price: '$899',
  },
  {
    id: 3,
    src : '/Assets/OfficeTable3.jpg',
    alt : 'Office Table',
    height: '100 cm',
    width: '200 cm',
    depth: '150 cm',
    weight: '80 kg',
    material: 'Wood',
    color: 'Dark Brown',
    price: '$899',
  },
  {
    id: 14,
    src : '/Assets/OfficeTable4.jpg',
    alt : 'Office Table',
    height: '100 cm',
    width: '200 cm',
    depth: '150 cm',
    weight: '80 kg',
    material: 'Wood',
    color: 'Dark Brown',
    price: '$899',
  },
]




